#!/bin/bash

echo "🧪 Testing Fueling Guidance Display System"
echo "==========================================="
echo ""

echo "1️⃣ Testing Queue API Endpoint..."
QUEUE_RESPONSE=$(curl -s "http://localhost:5000/api/fuel/queue/427194")
QUEUE_COUNT=$(echo "$QUEUE_RESPONSE" | jq -r '.count')
echo "   ✅ Queue endpoint working: $QUEUE_COUNT workouts in queue"
echo ""

echo "2️⃣ Sample Fueling Data:"
echo "$QUEUE_RESPONSE" | jq -r '.queue[:3] | .[] | "   📅 \(.workout_date) - \(.workout_title) (\(.workout_type)): \(.fuel_carb)g CHO, \(.fuel_fluid)ml fluid, \(.fuel_sodium)mg sodium"'
echo ""

echo "3️⃣ Fueling Text Format (for copy-paste):"
FIRST_WORKOUT=$(echo "$QUEUE_RESPONSE" | jq -r '.queue[0]')
CARB=$(echo "$FIRST_WORKOUT" | jq -r '.fuel_carb')
FLUID=$(echo "$FIRST_WORKOUT" | jq -r '.fuel_fluid')
SODIUM=$(echo "$FIRST_WORKOUT" | jq -r '.fuel_sodium')

cat << FUELING
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
   ⚡ ECHODEVO FUELING GUIDANCE ⚡

   CARBOHYDRATES: ${CARB}g/hr
   HYDRATION: ${FLUID}ml/hr
   SODIUM: ${SODIUM}mg/hr

   This guidance is auto-generated based on workout duration, intensity, and sport type.
   Adjust based on conditions (heat, altitude, personal sweat rate).

   ---
   Generated by Echodevo Adaptive Readiness Engine
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
FUELING
echo ""

echo "4️⃣ Dashboard Status:"
DASHBOARD_URL="https://5000-i8mf68r87mlc4fo6mi2yb-ad490db5.sandbox.novita.ai/static/coach"
echo "   🌐 URL: $DASHBOARD_URL"
echo "   📊 Athlete: Angela 1A (ID: 427194)"
echo "   📅 Current Week: $(date -d 'last monday' '+%Y-%m-%d') to $(date -d 'next sunday' '+%Y-%m-%d')"
echo ""

echo "✅ ALL SYSTEMS OPERATIONAL"
echo ""
echo "📖 How to use:"
echo "   1. Open dashboard: $DASHBOARD_URL"
echo "   2. Clear cache (Ctrl+Shift+R)"
echo "   3. Select Angela 1A"
echo "   4. Click '⚡ Fuel Next Week'"
echo "   5. Scroll to '💧 Fueling Guidance' section"
echo "   6. Click 'Copy' button for each workout"
echo "   7. Paste into TrainingPeaks Pre-Activity Comments"
echo ""
echo "📄 Full documentation: /home/user/webapp/FINAL_SOLUTION.md"
